### ISSUE TITLE
Bounding box of a layer does not get updated

### ISSUE THREAD

**Issue by fzadrazil** [LayerManager/layman#159]
New layer is being created with the bounding box of [0, 0, 0, 0] and bbox doesn't get updated after pushing new features to the layer. Any layer should be probably created with bbox coordinates that cover the whole world and then updated on layer edits.

- [x] Treat layers without any data (set world bbox), #166
- [x] Update bbox on data change (PATCH Layer, WFS-T)
- [x] Update layer thumbnail on data change (PATCH Layer, WFS-T), #170
- [x] Update map thumbnail on data change (PATCH Layer, WFS-T), #170
